"""add_selection_processes

Revision ID: a93f1858aac7
Revises: 875e3f246091
Create Date: 2026-07-13 21:05:16.035916

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a93f1858aac7"
down_revision: str | Sequence[str] | None = "875e3f246091"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "selection_processes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cargo", sa.String(length=100), nullable=False),
        sa.Column("nivel", sa.String(length=50), nullable=False),
        sa.Column("setor", sa.String(length=100), nullable=False),
        sa.Column("squad", sa.String(length=50), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["template_id"], ["exam_templates.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "exam_invitations", sa.Column("selection_process_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        op.f("ix_exam_invitations_selection_process_id"),
        "exam_invitations",
        ["selection_process_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "exam_invitations",
        "selection_processes",
        ["selection_process_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "exam_invitations", type_="foreignkey")
    op.drop_index(op.f("ix_exam_invitations_selection_process_id"), table_name="exam_invitations")
    op.drop_column("exam_invitations", "selection_process_id")
    op.drop_table("selection_processes")
    # ### end Alembic commands ###
