"""add_is_external_to_exam_invitations

Revision ID: f83e9bf8b061
Revises: 5bafedb2204e
Create Date: 2026-06-24 22:11:43.477644

"""

from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op

if TYPE_CHECKING:
    from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "f83e9bf8b061"
down_revision: str | Sequence[str] | None = "5bafedb2204e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("exam_invitations", sa.Column("is_external", sa.Boolean(), nullable=True))
    op.execute("UPDATE exam_invitations SET is_external = false WHERE is_external IS NULL")
    op.alter_column("exam_invitations", "is_external", nullable=False)
    op.create_index(
        op.f("ix_exam_invitations_is_external"), "exam_invitations", ["is_external"], unique=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_exam_invitations_is_external"), table_name="exam_invitations")
    op.drop_column("exam_invitations", "is_external")
    # ### end Alembic commands ###
